### ISSUE TITLE
memory.grow ambiguity

### ISSUE THREAD

**Issue by yamt** [WebAssembly/custom-page-sizes#18]
when page size is 1, 0xffffffff result from memory.grow is ambiguous when you tried to grow the memory size from 0xffffffff to 0x100000000.

**Comment by fitzgen** [comment]
This was indeed considered but it was [pointed out](https://github.com/WebAssembly/custom-page-sizes/pull/8#issuecomment-2045901551) that we have the same ambiguity with tables in Wasm today. Therefore, for consistency, we didn't add special cases for this edge case. It is always possible to check via `memory.size` after receiving `-1`/`0xffffffff` to disambiguate.

Does that resolve things for you?

**Comment by yamt** [comment]
> This was indeed considered but it was [pointed out](https://github.com/WebAssembly/custom-page-sizes/pull/8#issuecomment-2045901551) that we have the same ambiguity with tables in Wasm today. Therefore, for consistency, we didn't add special cases for this edge case.

ok. i agree it isn't necessarily worth fixing.

> It is always possible to check via `memory.size` after receiving `-1`/`0xffffffff` to disambiguate.

it's racy for shared memory. it's simpler to leak the last byte.

**Comment by yamt** [comment]
> > It is always possible to check via `memory.size` after receiving `-1`/`0xffffffff` to disambiguate.
> 
> it's racy for shared memory. it's simpler to leak the last byte.

after thinking about it a bit more, i suspect you can't use memory.size even for non-shared memory
because memory.size returns an i32, which can't represent 0x100000000.

anyway, as table has a similar issue as you pointed out, i opened a question in the spec repo.
https://github.com/WebAssembly/spec/issues/1752

**Comment by rossberg** [comment]
Since size 2^32 isn't possible, the only ambiguous case is growing a table/memory of size 2^32-1 by 0, which should succeed but whose result is indistinguishable from -1. In practice, growing by 0 is an odd case that shouldn't matter much.

**Comment by fitzgen** [comment]
I believe this has been addressed and can be closed.
