### ISSUE TITLE
A question about page size relocation

### ISSUE THREAD

**Issue by yamt** [WebAssembly/custom-page-sizes#21]
the overview states it's ideal to use a relocation for page size.
why do you prefer a relocation over eg. an immutable global?

**Comment by fitzgen** [comment]
Six of one, half a dozen of another. Both approaches should enable const-folding/-propagation and avoids accessing memory, which tends to inhibit compiler optimization.

**Comment by yamt** [comment]
if there is little differences, i guess it's simpler to use a global instead.

**Comment by fitzgen** [comment]
This was addressed in #22.
