### ISSUE TITLE
Heads up: Scheduling a vote for phase 2

### ISSUE THREAD

**Issue by fitzgen** [WebAssembly/custom-page-sizes#25]
This issue is an announcement for visibility: [I'm adding an agenda item to the 2024-07-30 CG meeting](https://github.com/WebAssembly/meetings/pull/1619) to give an update on the discussion in https://github.com/WebAssembly/custom-page-sizes/issues/13 and the prototype implementation status in Wasmtime as well as to vote for moving this proposal to phase 2.

As a reminder, these are [the phase 2 entry requirements](https://github.com/WebAssembly/meetings/blob/main/process/phases.md#2-feature-description-available-community--working-group):

> Entry requirements:
>
> * Precise and complete overview document is available in a forked repo around which a reasonably high level of consensus exists.
> * Updates to the actual spec document, test suite, and reference interpreter are NOT yet required.

If anyone believes that that there exists a better design for supporting smaller-than-64KiB memories, that an alternative approach hasn't received enough consideration, etc... please speak up well before then! Feel free to leave a comment here, open an issue in this repo, or reach out to me privately.

**Comment by tommie** [comment]
I made a quick implementation in wasm3: https://github.com/tommie/wasm3/tree/custom-page-size https://github.com/tommie/wasm3/commit/3d2dfb75129802080e8ea6ffe5b8eded651bda68

Since it's running on small devices (RP2040 for me,) having small page sizes is really useful. (That said, I made some PRs for fuzz-bugs others had found, which aren't being addressed, so I think wasm3 is about to die out.)

**Comment by fitzgen** [comment]
> I made a quick implementation in wasm3: https://github.com/tommie/wasm3/tree/custom-page-size [tommie/wasm3@3d2dfb7](https://github.com/tommie/wasm3/commit/3d2dfb75129802080e8ea6ffe5b8eded651bda68)
> 
> Since it's running on small devices (RP2040 for me,) having small page sizes is really useful.

Very cool! Thanks for sharing, will dig in a bit.

> (That said, I made some PRs for fuzz-bugs others had found, which aren't being addressed, so I think wasm3 is about to die out.)

Yeah, my understanding is that unfortunately the war in Ukraine has severely impacted wasm3's author. Terrible.

**Comment by fitzgen** [comment]
The vote happened and passed, so I will close this issue.

**Comment by vshymanskyy** [comment]
Yes, fuzz-bugs are currently not addressed due to a lack of resources.
Read more: https://x.com/wasm3_engine/status/1736712528883769670

Frankly, I have more interesting and financially rewarding tasks on my plate. At some point, Wasm3 may receive more attention and care.
