### ISSUE TITLE
Return type of memory.grow?

### ISSUE THREAD

**Issue by kripken** [WebAssembly/custom-page-sizes#28]
It [came up](https://github.com/WebAssembly/binaryen/pull/6733#issuecomment-2224074615) in a discussion on implementing memory64 that smaller page sizes may require a different return type for `memory.grow`.

`memory.grow`, even for memory64, returns an i32. An i32 is normally enough as 32 bits * the wasm page size of 16 bits means more memory than anyone could ask for (perhaps :smile: ) but if we had one-byte page sizes then we could only report on growing by up to `2^32 - 1` **bytes** instead of pages, which is not enough for memory64.

(I don't have a particular solution in mind, nor whether this is serious or not, just noting it here so we don't forget.)

**Comment by sbc100** [comment]
memoy.grow takes and returns i64 when then memory is 64-bit: https://github.com/WebAssembly/memory64/blob/main/proposals/memory64/Overview.md

Perhaps there was some previous version of the spec where that wasn't true?

**Comment by kripken** [comment]
No, probably just I was confused, sorry for the noise. Closing.
